[package]
name = "iruntime"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[dependencies]
tracing = "0.1"
hex_fmt = "0.3.0"
urlencoding = "2.1.0"
serde_json = "1.0.103"
base64 = "0.13.0"
anyhow = "1.0.69"
libc = "0.2"
num_cpus = "1.13"
version = "3.0.0"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
clap = { version = "4.0.19", features = ["derive"] }
lazy_static = { version = "1.4.0", default-features = false }
parity-scale-codec = { version = "3.3", default-features = false }
serde = { version = "1.0.171", default-features = false, features = ["derive"] }
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "socks", "blocking"] }
rocket_cors = { version = "0.6.0-alpha1", git = "https://github.com/lawliet89/rocket_cors" }

reqwest-env-proxy = { path = "../../crates/reqwest-env-proxy" }
indranet-sanitized-logger = { path = "../../crates/indranet-sanitized-logger" }
indratory = { path = "../../crates/indratory" }
# indratory-api = { path = "../../crates/indratory/api", features = ["pruntime-client"] }
# indratory-pal = { path = "../../crates/indratory/pal" }
# indranet-allocator = { path = "../../crates/indranet-allocator" }
# indranet-rocket-middleware = { path = "../../crates/indranet-rocket-middleware" }
# indranet-types = { path = "../../crates/indranet-types", features = ["enable_serde", "sgx"] }
# indranet-git-revision = { path = "../../crates/indranet-git-revision" }
# sgx-api-lite = { path = "../../crates/sgx-api-lite" }

[patch.crates-io]
# TODO.kevin: Move back to crates.io once it released 1.0
derive_more = { version = "0.99.17", git = "https://github.com/JelteF/derive_more" }

# For pink-extension-runtime, it will introduce Substrate from crates-io which usually different with polkadot-branch
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
