[package]
name = "mp-chain-id"
version = "0.7.0"
license = "MIT"
description = "Starknet chain ids"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

mp-felt = { path = "../felt", default-features = false }
starknet-ff = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e", features = ["alloc"] }

[features]
default = ["std"]
std = [
  "mp-felt/std",
]