[package]
name = "mp-chain-id"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Starknet chain ids"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara Primitives
mp-felt = { workspace = true }
# Starknet dependencies
starknet-ff = { workspace = true }

[features]
default = ["std"]
std = [
  "mp-felt/std",
]