[package]
name = "mp-felt"
version = "1.0.0"
description = "Madara felt type"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = "1.0.50"

sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
cairo-vm = { git = "https://github.com/bidzyyys/cairo-vm", branch = "feature/scale-codec", features = [
  "cairo-1-hints",
  "parity-scale-codec",
] }
starknet_api = { git = "https://github.com/bidzyyys/starknet-api", branch = "feature/scale-codec", features = [
  "testing",
  "parity-scale-codec",
] }
starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet-ff = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }

# Optional
hex = { version = "0.4.3", optional = true }
serde_with = { version = "2.3.3", optional = true }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"], optional = true }
serde = { version = "1.0.192", default-features = false, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "scale-info/std",
]

parity-scale-codec = ["dep:parity-scale-codec", "dep:hex"]
scale-info = ["dep:scale-info"]
serde = ["dep:serde", "starknet-ff/serde", "dep:serde_with"]