[package]
name = "pink-extension"
version = "0.1.0"
edition = "2018"
description = "ink! for writing Indra contracts"
license = "Apache-2.0"

[dependencies]
log = "0.4.17"
ink = { version = "4.2", default-features = false, features = ["ink-debug"] }
scale = { package = "parity-scale-codec", version = "3.3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
dlmalloc = { version = "0.2.4", default-features = false, features = ["global"], optional = true }

pink-extension-macro = { path = "./macro" }
this-crate = { path = "../../this-crate" }

[dev-dependencies]
insta = "1.7.2"

[features]
default = ["std", "runtime_utils", "ink-as-dependency"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
runtime_utils = ["std"]
dlmalloc = ["ink/no-allocator", "dep:dlmalloc"]
ink-as-dependency = []
