[package]
name = "mp-block"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "The starknet block"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
mp-felt = { workspace = true }
mp-hashers = { workspace = true }
mp-transactions = { workspace = true }
sp-core = { workspace = true }
starknet_api = { workspace = true }
thiserror = { workspace = true }

# Optionals
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-core/std",
  "mp-felt/std",
  "mp-hashers/std",
  "mp-transactions/std"
]
parity-scale-codec = ["dep:parity-scale-codec", "mp-felt/parity-scale-codec"]
serde = ["dep:serde"]
scale-info = ["dep:scale-info", "mp-felt/scale-info"]
