[package]
name = "pink-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15"
once_cell = "1"
libc = "0.2"
log = "0.4"
tracing = "0.1"
environmental = "1"
serde = { version = "1", features = ["derive"] }

sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

pink-capi = { path = "../capi" }
pink-extension-runtime = { path = "../pink-extension-runtime" }
indranet-crypto = { path = "../../indranet-crypto" }

[dev-dependencies]
pink = { path = "../runtime" }
scale = { package = "parity-scale-codec", version = "3.1", default-features = false, features = [
    "derive",
] }
insta = "1"
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
env_logger = "0.10.0"
assert_matches = "1.5.0"
