[package]
name = "sidevm-macro"
version = "0.1.0"
edition = "2021"
description = "Macros for writing indra contract sidevm program"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut", "extra-traits", "parsing"] }
heck = "0.4.0"

[dev-dependencies]
insta = "1.14.0"
rustfmt-snippet = { version = "0.1.0" }
