[package]
name = "pink"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
sha2 = "0.10.2"
log = "0.4.14"
tracing = "0.1"
hash-db = "0.16.0"
anyhow = "1"
paste = "1.0"
wat = "1.0"
call-trace = "*"
impl-serde = "0.4.0"
hex = "0.4.3"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.67"
environmental = "1.1.3"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks", "blocking",] }
indranet-serde-more = { path = "../../indranet-serde-more" }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive", "serde", "decode"] }
parity-wasm = { version = "0.45.0", default-features = false }
wasmi-validation = { version = "0.5.0", default-features = false }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-contracts-proc-macro = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

pink-extension = { path = "../pink-extension" }
pink-extension-runtime = { path = "../pink-extension-runtime" }
pink-capi = { path = "../capi" }
reqwest-env-proxy = { path = "../../reqwest-env-proxy" }
indranet-trie-storage = { path = "../../indranet-trie-storage" }
indranet-types = { path = "../../indranet-types" }
indranet-crypto = { path = "../../indranet-crypto" }
indranet-sanitized-logger = { path = "../../indranet-sanitized-logger" }
indranet-git-revision = { path = "../../indranet-git-revision" }
indranet-wasm-checker = { path = "../../indranet-wasm-checker" }

[dev-dependencies]
insta = "1.7.2"
hex-literal = "0.3.3"
