
[package]
name = "mc-storage"
version = "0.7.0"
edition.workspace = true
description = "Starknet storage compatibility layer for Substrate."
authors = [
  "Timothée Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"

[dependencies]
blockifier = { workspace = true }
frame-support = { workspace = true }
mp-storage = { workspace = true }
pallet-starknet-runtime-api = { workspace = true }
parity-scale-codec = { workspace = true }
sc-client-api = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-storage = { workspace = true }
starknet_api = { workspace = true }
