[package]
name = "mp-sequencer-address"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Sequencer address inherent logic"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { workspace = true }
sp-inherents = { workspace = true }
thiserror = { workspace = true }

# Optional
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "sp-inherents/std",
  "sp-core/std",
]
parity-scale-codec = ["dep:parity-scale-codec"]
client = ["parity-scale-codec", "dep:async-trait"]
