[package]
name = "mp-sequencer-address"
version = "0.7.0"
license = "MIT"
description = "Sequencer address inherent logic"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = "1.0.50"

sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }

# Optional
async-trait = { version = "0.1.74", optional = true }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "sp-inherents/std",
  "sp-core/std",
]
parity-scale-codec = ["dep:parity-scale-codec"]
client = ["parity-scale-codec", "dep:async-trait"]