[package]
name = "pallet-operations"
version = "0.1.0"
edition.workspace = true
authors = ["Cardinal", "Aleph Zero Foundation"]
homepage = "https://alephzero.org"
repository = "https://github.com/Cardinal-Cryptography/aleph-node"

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
log = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-session = { workspace = true }
pallet-balances = { workspace = true }
pallet-staking = { workspace = true }
pallet-contracts = { workspace = true }

sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-staking = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true }
pallet-timestamp = { workspace = true }
frame-election-provider-support = { workspace = true }
anyhow = "1.0.93"
wat = "1"

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
    "log/std",

    "frame-support/std",
    "frame-system/std",
    "pallet-session/std",
    "pallet-balances/std",
    "pallet-staking/std",
    "pallet-contracts/std",
    "pallet-timestamp/std",
    "frame-election-provider-support/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-staking/std",
    "sp-std/std",
]

try-runtime = [
    "frame-support/try-runtime",
]
