[package]
name = "mp-genesis-config"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition.workspace = true
repository = "https://github.com/keep-starknet-strange/madara/"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { workspace = true }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
  "serde/std",
  "mp-felt/std",
]