[package]
name = "mp-genesis-config"
version = "0.7.0"
license = "MIT"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "0.4.3" }
serde = { version = "1.0.192", default-features = false, features = ["derive"] }
serde_with = { version = "2.3.3" }

mp-felt = { path = "../felt", default-features = false, features = ["parity-scale-codec", "serde"] }
starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e", features = ["alloc"] }

[features]
default = ["std"]
std = [
  "serde/std",
  "mp-felt/std",
]