[package]
name = "pallet-starknet"
version.workspace = true
edition.workspace = true
description = "FRAME pallet to execute Starknet contracts."
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
homepage = "https://github.com/keep-starknet-strange/madara"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Madara primitives
mp-block = { workspace = true }
mp-chain-id = { workspace = true }
mp-digest-log = { workspace = true }
mp-felt = { workspace = true, features = ["parity-scale-codec", "serde"] }
mp-genesis-config = { workspace = true }
mp-hashers = { workspace = true }
mp-program-hash = { workspace = true }
mp-sequencer-address = { workspace = true, features = ["parity-scale-codec"] }
mp-simulations = { workspace = true, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-storage = { workspace = true, features = ["parity-scale-codec"] }
mp-transactions = { workspace = true, features = ["scale-info"] }

blockifier = { workspace = true, features = ["testing"] }
cairo-vm = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true, features = ["alloc"] }
starknet_api = { workspace = true }

# Other third party dependencies
log = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Optional deps
cairo-lang-starknet-classes = { workspace = true, optional = true }

[dev-dependencies]
pallet-timestamp = { workspace = true }
pretty_assertions = { workspace = true }
test-case = "3.1.0"
lazy_static = "1.4.0"
hexlit = "0.5.5"
assert_matches = "1.5.0"
starknet-ff = { workspace = true }
project-root = "0.2.2"

[features]
default = ["std", "genesis-loader"]
std = [
    "serde/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "mp-block/std",
    "mp-chain-id/std",
    "mp-digest-log/std",
    "mp-felt/std",
    "mp-genesis-config/std",
    "mp-hashers/std",
    "mp-program-hash/std",
    "mp-sequencer-address/std",
    "mp-simulations/std",
    "mp-storage/std",
    "mp-transactions/std",
]
genesis-loader = ["dep:cairo-lang-starknet-classes"]
runtime-benchmarks = []
try-runtime = ["frame-support/try-runtime"]