[package]
name = "pallet-starknet"
version = "1.0.0"
description = "FRAME pallet to execute Starknet contracts."
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.20" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.192", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.108" }

sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-io = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-runtime = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
sp-std = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-support = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
frame-system = {  git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }

mp-block = { path = "./primitives/block", default-features = false }
mp-chain-id = { path = "./primitives/chain-id", default-features = false }
mp-digest-log = { path = "./primitives/digest-log", default-features = false }
mp-felt = { path = "./primitives/felt", features = ["parity-scale-codec", "serde"], default-features = false }
mp-genesis-config = { path = "./primitives/genesis-config", default-features = false }
mp-hashers = { path = "./primitives/hashers", default-features = false }
mp-program-hash = { path = "./primitives/program-hash", default-features = false }
mp-sequencer-address = { path = "./primitives/sequencer-address", default-features = false, features = ["parity-scale-codec"] }
mp-simulations = { path = "./primitives/simulations", default-features = false, features = [
  "parity-scale-codec",
  "scale-info",
] }
mp-storage = { path = "./primitives/storage", default-features = false, features = ["parity-scale-codec"] }
mp-transactions = { path = "./primitives/transactions", default-features = false, features = ["scale-info"] }

blockifier = { git = "https://github.com/bidzyyys/blockifier", features = ["testing"] }
cairo-vm = { git = "https://github.com/bidzyyys/cairo-vm", branch = "feature/scale-codec", features = [
  "cairo-1-hints",
  "parity-scale-codec",
] }

starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet_api = { git = "https://github.com/bidzyyys/starknet-api", branch = "feature/scale-codec", features = [
  "testing",
  "parity-scale-codec",
] }

# Optional deps
cairo-lang-starknet-classes = { git = "https://github.com/bidzyyys/cairo.git", branch = "feature/scale-codec", optional = true }

[dev-dependencies]
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0" }
starknet-ff = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
pretty_assertions = "1.4.0"
test-case = "3.1.0"
lazy_static = "1.4.0"
hexlit = "0.5.5"
assert_matches = "1.5.0"
project-root = "0.2.2"

[features]
default = ["std"]
std = [
    "serde/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "mp-block/std",
    "mp-chain-id/std",
    "mp-digest-log/std",
    "mp-felt/std",
    "mp-genesis-config/std",
    "mp-hashers/std",
    "mp-program-hash/std",
    "mp-sequencer-address/std",
    "mp-simulations/std",
    "mp-storage/std",
    "mp-transactions/std",
]
genesis-loader = ["dep:cairo-lang-starknet-classes"]
runtime-benchmarks = []
try-runtime = ["frame-support/try-runtime"]