[workspace]
members = [
    "cli",
    "codegen",
    "examples",
    "testing/test-runtime",
    "testing/integration-tests",
    "testing/ui-tests",
    "macro",
    "metadata",
    "subxt"
]
exclude = ["testing/wasm-tests"]
resolver = "2"

[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
rust-version = "1.64.0"
license = "Apache-2.0 OR GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
