[package]
name = "mp-transactions"
version = "0.7.0"
license = "MIT"
description = "Starknet primitives for Substrate."
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
indexmap = "2.2.5"
log = "0.4.20"
sha3 = { version = "0.10.8" }
flate2 = { version = "1.0.28", optional = true }
num-bigint = { version ="0.4.4", optional = true }
serde_json = { version = "1.0.108", optional = true }
thiserror = { version = "1.0.50", optional = true }

sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.3.0", default-features = false }
blockifier = { git = "https://github.com/bidzyyys/blockifier", branch = "feature/scale-codec" }
cairo-vm = { git = "https://github.com/bidzyyys/cairo-vm", branch = "feature/scale-codec", features = [
  "cairo-1-hints",
  "parity-scale-codec",
] }

mp-felt = { path = "../felt", default-features = false }
mp-hashers = { path = "../hashers", default-features = false }
starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e", features = ["alloc"] }
starknet-ff = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e", features = ["alloc"] }
starknet_api = { git = "https://github.com/bidzyyys/starknet-api", branch = "feature/scale-codec", features = [
  "testing",
  "parity-scale-codec",
] }

# Other optional
cairo-lang-starknet-classes = { git = "https://github.com/bidzyyys/cairo.git", branch = "feature/scale-codec", optional = true }
cairo-lang-utils = { git = "https://github.com/bidzyyys/cairo.git", branch = "feature/scale-codec", optional = true }

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"], optional = true }
serde = { version = "1.0.192", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
assert_matches = "1.5.0"

[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-core/std",
  "mp-felt/std",
  "mp-hashers/std"
]

client = [
  "dep:flate2",
  "dep:cairo-lang-utils",
  "dep:num-bigint",
  "dep:serde_json",
  "dep:thiserror",
  "dep:cairo-lang-starknet-classes",
]
parity-scale-codec = [
  "dep:parity-scale-codec",
  "starknet_api/parity-scale-codec",
  "mp-felt/parity-scale-codec",
]
scale-info = [
  "dep:scale-info",
  "mp-felt/scale-info",
  "starknet_api/scale-info",
  "blockifier/scale-info",
]
serde = ["dep:serde", "mp-felt/serde"]