[package]
name = "mp-digest-log"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Primitives for Madara digest logs"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[dependencies]
mp-block = { workspace = true, features = ["parity-scale-codec"] }
parity-scale-codec = { workspace = true }
sp-runtime = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
blockifier = { workspace = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "sp-runtime/std",
  "mp-block/std",
]