[package]
name = "mc-db"
version = "0.7.0"
edition.workspace = true
authors = [
  "Timothée Delabrouille <https://github.com/tdelabro>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
repository = "https://github.com/keep-starknet-strange/madara/"
license = "MIT"
description = "Starknet database backend"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
kvdb-rocksdb = { version = "0.19.0", optional = true }
log = { workspace = true }
parity-db = { version = "0.4.12", optional = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
sc-client-db = { workspace = true, features = ["rocksdb"] }
sp-database = { workspace = true }
sp-runtime = { workspace = true }
starknet_api = { workspace = true }
thiserror = { workspace = true }
uuid = "1.7.0"

[features]
default = ["kvdb-rocksdb", "parity-db"]
