[package]
name = "subxt-macro"
version = "0.28.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
rust-version = "1.64.0"
publish = true

license = "Apache-2.0 OR GPL-3.0"
readme = "../README.md"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Generate types and helpers for interacting with Substrate runtimes."

[lib]
proc-macro = true

[dependencies]
darling = "0.14.4"
proc-macro-error = "1.0.4"
syn = "1.0.109"

subxt-codegen = { path = "../codegen", version = "0.28.0" }
