[package]
name = "subxt-macro"
version = "0.28.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = true
autotests = false

license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
description = "Generate types and helpers for interacting with Substrate runtimes."

[lib]
proc-macro = true

[dependencies]
darling = "0.14.4"
proc-macro-error = "1.0.4"
syn = "1.0.109"

subxt-codegen = { path = "../codegen", version = "0.28.0" }
