[package]
name = "mc-genesis-data-provider"
version = "0.7.0"
edition.workspace = true
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
jsonrpsee = { workspace = true }
log = { workspace = true }
mp-genesis-config = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
