[package]
name = "mp-simulations"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Starknet chain ids"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blockifier = { workspace = true }
starknet-core = { workspace = true }

# Optional dependencies
parity-scale-codec = { workspace = true, optional = true }
scale-info = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "parity-scale-codec/std",
  "scale-info/std",
]
parity-scale-codec = ["dep:parity-scale-codec"]
scale-info = ["dep:scale-info"]
