[package]
name = "pallet-evm"
version = "2.16.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false }
hex-literal = { version = "0.4.1" }
ripemd160 = { version = "0.9", default-features = false }
rlp = { version = "0.5.2", default-features = false }
serde = { version = "1.0.145", optional = true, features = ["derive"] }
sha3 = { version = "0.9.1", default-features = false }
tiny-keccak = { version = "2.0", features = ["fips202"] }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"], optional = true }
hex = { version = "0.4.3", default-features = false, features = ["alloc"], optional = true }
num = { version = "0.4", features = ["alloc"], default-features = false }
bn = { package = "substrate-bn", version = "0.6", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false, optional = true }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }

pallet-support = { package = "pallets-support", path = "../support", default-features = false }
pallet-evm-utility = { path = "utility", default-features = false }
primitives = { package = "selendra-primitives", path = "../../primitives", default-features = false }
pallet-idle-scheduler = { path = "../idle-scheduler", default-features = false, optional = true }

[dev-dependencies]
hex = "0.4.3"
env_logger = "0.10.0"
serde_json = "1.0.68"
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }

[features]
default = ["std"]
std = [
	"serde",
	"num/std",
	"rlp/std",
	"sha3/std",
	"ripemd160/std",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm-utility/std",
	"pallet-idle-scheduler/std",
	"pallet-support/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"primitives/std",
	
]
with-ethereum-compatibility = []
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-idle-scheduler/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-timestamp/try-runtime",
]
tracing = ["pallet-evm-utility/tracing"]
bench = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex",
	"pallet-idle-scheduler",
	"pallet-balances",
	"serde_json",
	"sp-runtime/runtime-benchmarks",
]