[package]
name = "mp-storage"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Starknet substrate storage const and types"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Optional
lazy_static = { workspace = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
], optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sp-io = { workspace = true }


[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "sp-io/std",
]
serde = ["dep:serde"]
parity-scale-codec = ["dep:parity-scale-codec"]
