[package]
name = "indranet-sanitized-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10.0"
tracing-core = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
