[package]
name = "mp-hashers"
version = "0.7.0"
edition.workspace = true
license = "MIT"
description = "Starknet hashers"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
repository = "https://github.com/keep-starknet-strange/madara/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
mp-felt = { workspace = true }
starknet-core = { workspace = true }
starknet-crypto = { workspace = true }

# Optional
parity-scale-codec = { workspace = true, optional = true }
scale-info = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "mp-felt/std",
]

parity-scale-codec = ["dep:parity-scale-codec", "mp-felt/parity-scale-codec"]
scale-info = ["dep:scale-info", "mp-felt/scale-info"]
serde = ["dep:serde", "mp-felt/serde"]
