[package]
name = "mp-hashers"
version = "0.7.0"
license = "MIT"
description = "Starknet hashers"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
mp-felt = { path = "../felt", default-features = false }
starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", rev = "2d59636911628260fa460179010bbd00e89de06e" }

# Optional
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"], optional = true }
serde = { version = "1.0.192", default-features = false, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
  "serde/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "mp-felt/std",
]
parity-scale-codec = ["dep:parity-scale-codec", "mp-felt/parity-scale-codec"]
scale-info = ["dep:scale-info", "mp-felt/scale-info"]
serde = ["dep:serde", "mp-felt/serde"]