[package]
name = "sidevm-env"
version = "0.1.0"
edition = "2021"
description = "The low level protocol between sidevm guest and host"
license = "Apache-2.0"

[dependencies]
cfg-if = "1.0.0"
derive_more = "0.99.17"
num_enum = "0.5.7"
log = "0.4.16"
futures = "0.3"
tinyvec = { version = "1.5.1", features = ["alloc"] }
scale = { package = "parity-scale-codec", version = "3.3", default-features = false, features = ["derive", "std"] }
sidevm-macro = { version = "0.1.0", path = "../macro" }

[features]
host = []
